In [1]:
import pickle
import numpy as np

from tensorflow import keras
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split



2025-01-27 21:06:12.274106: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
with open("../../pickles/X_train_aug.pkl", "rb") as file:
    X_train = pickle.load(file)

with open("../../pickles/y_train_aug.pkl", "rb") as file:
    y_train = pickle.load(file)

with open("../../pickles/labels.pkl", "rb") as file:
    labels = pickle.load(file)

with open("../../pickles/resized_images.pkl", "rb") as file:
    resized = pickle.load(file)



In [3]:

print(X_train[0])
print(y_train[0])
print(labels[0])


[[[0.16078432 0.22352941 0.11764706]
  [0.08235294 0.14509805 0.04313726]
  [0.2627451  0.30588236 0.24313726]
  ...
  [0.21568628 0.4509804  0.6862745 ]
  [0.40784314 0.6039216  0.8117647 ]
  [0.4627451  0.6313726  0.83137256]]

 [[0.39215687 0.44313726 0.34117648]
  [0.02745098 0.07450981 0.        ]
  [0.03137255 0.0627451  0.00392157]
  ...
  [0.07058824 0.30980393 0.5568628 ]
  [0.2509804  0.45490196 0.6901961 ]
  [0.32941177 0.52156866 0.7490196 ]]

 [[0.06666667 0.09019608 0.        ]
  [0.17254902 0.19215687 0.10588235]
  [0.02745098 0.04313726 0.        ]
  ...
  [0.05490196 0.31764707 0.5921569 ]
  [0.15294118 0.3882353  0.6627451 ]
  [0.2        0.42352942 0.69411767]]

 ...

 [[0.03137255 0.0627451  0.        ]
  [0.03921569 0.07058824 0.        ]
  [0.10588235 0.15686275 0.04705882]
  ...
  [0.1882353  0.23921569 0.06666667]
  [0.21960784 0.26666668 0.07843138]
  [0.19215687 0.24313726 0.03529412]]

 [[0.10196079 0.11764706 0.0627451 ]
  [0.13725491 0.16470589 0.10196079]


In [4]:
print(np.unique(y_train))  # Ensure this matches expected labels (0 to 5)


[0 1 2 3 4 5]


In [ ]:
y_encoder = LabelEncoder().fit(y_train)
y = y_encoder.transform(y_train)

# Convert values to numpy arrays
X = np.array(X_train)

# Split the training dataset into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

model = keras.Sequential([
    layers.Input(shape=(150, 150, 3)),  
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(6, activation='softmax')  # ✅ Change output layer to match number of classes (6)
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
batch_size = 32
epochs = 10
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=epochs
)

Epoch 1/10
184/682 ━━━━━━━━━━━━━━━━━━━━ 6:59 843ms/step - accuracy: 0.4747 - loss: 1.4348